apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ template "rating.database" . }}
  labels:
{{ include "rating.labels" . | indent 4 }}
spec:
  replicas: 1
  serviceName: "{{ template "rating.database" . }}"
  selector:
    matchLabels:
{{ include "rating.matchLabels" . | indent 6 }}
      app: database
      version: {{ .Values.database.image.tag }}
  template:
    metadata:
      labels:
{{ include "rating.matchLabels" . | indent 8 }}
        app: database
        version: {{ .Values.database.image.tag }}
    spec:
      securityContext:
        runAsUser: 999
        fsGroup: 999
      initContainers:
      # with "fsGroup" set, each time a volume is mounted, Kubernetes must recursively chown() and chmod() all the files and directories inside the volume
      # this causes the postgresql reports the "data directory /var/lib/postgresql/data/pgdata has group or world access" issue when using some CSIs e.g. Ceph
      # use this init container to correct the permission
      # as "fsGroup" applied before the init container running, the container has enough permission to execute the command
      - name: "data-permissions-ensurer"
        image: {{ .Values.database.image.repository }}:{{ .Values.database.image.tag }}
        command: [ "/bin/sh" ]
        args: [ "-c", "chmod 700 /var/lib/postgresql/data/pg13 || true" ]
        volumeMounts:
          - name: database-data
            mountPath: /var/lib/postgresql/data
            subPath: {{ .Values.persistence.persistentVolumeClaim.database.subPath }}
      containers:
        - name: database
          image: "{{ .Values.database.image.repository }}:{{ .Values.database.image.tag }}"
          imagePullPolicy: {{ .Values.imagePullPolicy }}
          livenessProbe:
            exec:
              command:
                - /docker-healthcheck.sh
            initialDelaySeconds: 300
            periodSeconds: 10
          readinessProbe:
            exec:
              command:
                - /docker-healthcheck.sh
            initialDelaySeconds: 1
            periodSeconds: 10
          volumeMounts:
          - name: database-data
            mountPath: /var/lib/postgresql/data
            subPath: {{ .Values.persistence.persistentVolumeClaim.database.subPath }}
  volumeClaimTemplates:
    - metadata:
        name: "database-data"
        labels:
{{ include "rating.labels" . | indent 10 }}
      spec:
        accessModes: [{{ .Values.persistence.persistentVolumeClaim.database.accessMode | quote }}]
        {{- if .Values.persistence.persistentVolumeClaim.database.storageClass }}
        {{- if (eq "-" .Values.persistence.persistentVolumeClaim.database.storageClass) }}
        storageClassName: ""
        {{- else }}
        storageClassName: "{{ .Values.persistence.persistentVolumeClaim.database.storageClass }}"
        {{- end }}
        {{- end }}
        resources:
          requests:
            storage: {{ .Values.persistence.persistentVolumeClaim.database.size | quote }}
