apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: {{ template "bookinfo.zookeeper" . }}
  labels:
{{ include "bookinfo.labels" . | indent 4 }}
spec:
  hosts:
    - {{ template "bookinfo.zookeeper" . }}
  tcp:
    - match:
        - port: {{ template "bookinfo.zookeeper.servicePort" . }}
      route:
        - destination:
            host: {{ template "bookinfo.zookeeper" . }}
            port:
              number: {{ template "bookinfo.zookeeper.containerPort" . }}