apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: {{ template "bookinfo.rating" . }}
  labels:
{{ include "bookinfo.labels" . | indent 4 }}
spec:
  host: {{ template "bookinfo.rating" . }}
  subsets:
    - name: {{ template "bookinfo.istio.destRule.stableName" . }}
      labels:
        version: v1
    - name: {{ template "bookinfo.istio.destRule.canaryName" . }}
      labels:
        version: v