{{- if eq .Values.eventing.type "internal" -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ template "bookinfo.kafka" . }}
  labels:
{{ include "bookinfo.labels" . | indent 4 }}
    component: kafka
spec:
  selector:
{{ include "bookinfo.matchLabels" . | indent 4 }}
    component: kafka
  ports:
    - port: {{ template "bookinfo.kafka.servicePort" . }}
      targetPort: {{ template "bookinfo.kafka.containerPort" . }}
  clusterIP: None
{{- end -}}