{{- if eq .Values.eventing.type "internal" -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "bookinfo.zookeeper" . }}
  labels:
{{ include "bookinfo.labels" . | indent 4 }}
    components: zookeeper
spec:
  replicas: 1
  selector:
    matchLabels:
{{ include "bookinfo.matchLabels" . | indent 6 }}
      component: zookeeper
  template:
    metadata:
      labels:
{{ include "bookinfo.matchLabels" . | indent 8 }}
        component: zookeeper
    spec:
      containers:
        - name: zookeeper
          image: "{{ .Values.eventing.internal.zookeeper.image.repository }}:{{ .Values.eventing.internal.zookeeper.image.tag }}"
          imagePullPolicy: {{ .Values.imagePullPolicy }}
          env:
            - name: ALLOW_ANONYMOUS_LOGIN
              value: "yes"
          ports:
            - containerPort: {{ template "bookinfo.zookeeper.containerPort" . }}
          resources:
            requests:
              cpu: {{ .Values.eventing.internal.zookeeper.resources.requests.cpu }}
              memory: {{ .Values.eventing.internal.zookeeper.resources.requests.memory }}
            limits:
              cpu: {{ .Values.eventing.internal.zookeeper.resources.limits.cpu }}
              memory: {{ .Values.eventing.internal.zookeeper.resources.limits.memory }}
{{- end -}}