apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: {{ template "bookinfo.istio.ingressVirtualService" . }}
  labels:
{{ include "bookinfo.labels" . | indent 4 }}
spec:
  hosts:
    - {{ .Values.externalDomain }}
  gateways:
    - {{ template "bookinfo.istio.ingressGateway" . }}
  http:
    - name: core
      match:
        - uri:
            prefix: /api/books
      route:
        - destination:
            host: {{ template "bookinfo.core" . }}
            port:
              number: 8080
    - name: rating
      match:
        - uri:
            prefix: /api/rating
      route:
        - destination:
            host: {{ template "bookinfo.rating" . }}
            port:
              number: 8080
    - name: orders
      match:
        - uri:
            prefix: /api/orders
      route:
        - destination:
            host: {{ template "bookinfo.order" . }}
            port:
              number: 8080