apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: bookinfo-ingress-gateway
  labels:
{{ include "bookinfo.labels" . | indent 4 }}
spec:
  selector:
{{ include "bookinfo.istio.ingressGatwayMatchLabels" . | indent 4 }}
  servers:
  - port:
      number: 80
      name: http
      protocol: HTTP
    hosts:
    - {{ .Values.istio.externalDomain }}