apiVersion: v1
kind: Service
metadata:
  name:  {{ template "core.app" . }}-stable
  labels:
{{ include "core.labels" . | indent 4 }}
spec:
  ports:
    - port: {{ template "core.app.servicePort" . }}
      targetPort: {{ template "core.app.containerPort" . }}
      name: http-rest
  selector:
{{ include "core.matchLabels" . | indent 4 }}
    app: {{ template "core.app" . }}
---
apiVersion: v1
kind: Service
metadata:
  name:  {{ template "core.app" . }}-canary
  labels:
{{ include "core.labels" . | indent 4 }}
spec:
  ports:
    - port: {{ template "core.app.servicePort" . }}
      targetPort: {{ template "core.app.containerPort" . }}
      name: http-rest
  selector:
{{ include "core.matchLabels" . | indent 4 }}
    app: {{ template "core.app" . }}
