apiVersion: v1
kind: Service
metadata:
  name: {{ template "rating.database" . }}-svc
  labels:
{{ include "rating.labels" . | indent 4 }}
spec:
  ports:
    - port: 5432
      name: tcp-database
  selector:
{{ include "rating.matchLabels" . | indent 4 }}
    app: {{ template "rating.app" . }}
  clusterIP: None