apiVersion: v1
kind: Service
metadata:
  name:  {{ template "bookinfo.zookeeper" . }}
  labels:
{{ include "bookinfo.labels" . | indent 4 }}
spec:
  selector:
{{ include "bookinfo.matchLabels" . | indent 4 }}
    app: zookeeper
    version: {{ .Values.zookeeper.image.tag }}
  ports:
    - port: {{ template "bookinfo.zookeeper.servicePort" . }}
      targetPort: {{ template "bookinfo.zookeeper.containerPort" . }}
      name: tcp-zookeeper
  type: ClusterIP
