apiVersion: v1
kind: Service
metadata:
  name: {{ template "core.database" . }}-svc
  labels:
{{ include "core.labels" . | indent 4 }}
spec:
  ports:
    - port: 5432
      name: tcp-database
  selector:
{{ include "core.matchLabels" . | indent 4 }}
    app: {{ template "core.database" . }}
  clusterIP: None