apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: {{ template "bookinfo.istio.egressGateway" . }}
  labels:
{{ include "bookinfo.labels" . | indent 4 }}
spec:
  selector:
{{ include "bookinfo.istio.egressGatwayMatchLabels" . | indent 4 }}
  servers:
    - port:
        number: 80
        name: http
        protocol: HTTP
      hosts:
        - {{ template "bookinfo.upstream.payment" . }}