apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: {{ template "bookinfo.core.virtualservice" . }}
  labels:
{{ include "bookinfo.labels" . | indent 4 }}
spec:
  hosts:
    - {{ .Values.externalDomain }}
  gateways:
    - {{ template "bookinfo.istio.ingressGateway" . }}
  http:
    - name: core
      match:
        - uri:
            prefix: /api/books
      route:
        - destination:
            host: {{ template "bookinfo.core" . }}
            port:
              number: 8080
          weight: {{ sub 100 .Values.core.rolloutPolicy.canary.ratio }}
        - destination:
            host: {{ template "bookinfo.core" . }}-canary
            port:
              number: 8080
          weight: {{ .Values.core.rolloutPolicy.canary.ratio }}