apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: {{ template "rating.app" . }}
  labels:
{{ include "rating.labels" . | indent 4 }}
spec:
  replicas: {{ .Values.rating.replicas }}
  revisionHistoryLimit: {{ .Values.rating.revisionHistoryLimit }}
  selector:
    matchLabels:
{{ include "rating.matchLabels" . | indent 6 }}
      app: {{ template "rating.app" . }}
      release: {{ .Release.Name }}
  strategy:
    canary:
      trafficRouting:
        istio:
          virtualService:
            name: {{ template "rating.app" . }}-vs
            routes:
              - {{ template "rating.app" . }}-route1
          destinationRule:
            name: {{ template "rating.app" . }}-destrule
            canarySubsetName: canary
            stableSubsetName: stable
      steps:
        - setWeight: {{ .Values.rating.rolloutPolicy.canary.ratio }}
        - pause:
            duration: {{ .Values.rating.rolloutPolicy.canary.pause.duration }}
  template:
    metadata:
      labels:
{{ include "rating.matchLabels" . | indent 8 }}
        app: {{ template "rating.app" . }}
        release: {{ .Release.Name }}
    spec:
      containers:
        - name: rating
          image: "{{ .Values.rating.image.repository }}:{{ .Values.rating.image.tag }}"
          imagePullPolicy: {{ .Values.imagePullPolicy }}
          envFrom:
            - configMapRef:
                name: {{ template "rating.app" . }}-config
          ports:
            - containerPort: {{ template "rating.app.containerPort" . }}
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
          volumeMounts:
            - name: conf
              mountPath: /app/application.properties
              subPath: application.properties
      volumes:
        - name: conf
          configMap:
            name: {{ template "rating.app" . }}-config
            items:
              - key: application.properties
                path: application.properties

