apiVersion: v1
kind: Service
metadata:
  name: {{ template "rating.app" . }}-svc
  labels:
{{ include "rating.labels" . | indent 4 }}
spec:
  ports:
  - port: {{ template "rating.app.servicePort" . }}
    targetPort: {{ template "rating.app.containerPort" . }}
    name: http-rest
  selector:
{{ include "rating.matchLabels" . | indent 4 }}
    app: {{ template "rating.app" . }}