apiVersion: v1
kind: Service
metadata:
  name: {{ template "order.database" . }}
  labels:
{{ include "order.labels" . | indent 4 }}
spec:
  ports:
    - port: 5432
      name: tcp-database
  selector:
{{ include "order.matchLabels" . | indent 4 }}
    app: {{ template "order.database" . }}
  clusterIP: None